version: '3'
services:
  database:
    container_name: wolf-database
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wolf
    volumes:
      - ../server/script/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
  server:
    container_name: wolf-server
    image: igeeky/wolf-server
    restart: always
    ports:
      - "10080:10080"
    depends_on:
      - database
    environment:
      RBAC_ROOT_PASSWORD: wolf-123456
      RBAC_TOKEN_KEY: f40215a5f25cbb6d36df07629aaf1172240fe48d
      WOLF_CRYPT_KEY: fbd4962351924792cb5e5b131435cd30b24e3570
      RBAC_SQL_URL:  postgres://root:123456@database:5432/wolf
      CLIENT_CHANGE_PWD: "no"
    command: npm run start
  agent-or:
    container_name: wolf-agent-or
    image: igeeky/wolf-agent
    restart: always
    ports:
     - "10082:10082"
    depends_on:
      - server
    environment:
      BACKEND_URL: http://openresty.org
      RBAC_SERVER_URL: http://server:10080
      RBAC_APP_ID: openresty
  restful-demo:
    container_name: restful-demo
    image: igeeky/restful-demo:latest
    restart: always
    ports:
     - "10090:10090"
  agent-demo:
    container_name: wolf-agent-demo
    image: igeeky/wolf-agent
    restart: always
    ports:
     - "10084:10084"
    depends_on:
      - server
      - restful-demo
    environment:
      BACKEND_URL: http://restful-demo:10090
      RBAC_SERVER_URL: http://server:10080
      RBAC_APP_ID: restful-demo
      AGENT_PORT: 10084
      EXTENSION_CONFIG: include /opt/wolf/agent/conf/no-permission-demo.conf;